<a href="https://colab.research.google.com/github/Melissa-Etes/Sprint2_grupo54/blob/main/EC_Sprint2_HospiDataSUS_Clusterizacao_Grupo54.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Etapa Clusters - DataSUS - Grupo 54 (Sprint 2 FIAP)

##### Carregando Dados do GitHub

In [3]:
dados = pd.read_csv('https://raw.githubusercontent.com/Melissa-Etes/Sprint2_grupo54/main/data/internacoes_tratado.csv')
dados.head()

,COD_MUNICIPIO,MUNICIPIO,QTD_INTERNACOES,PERMANENCIA_MEDIA,TAXA_MORTALIDADE_PCT,VALOR_MEDIO_INTERNACAO,QTD_ESTAB_HOSPITALARES,POPULACAO,INTERNACOES_POR_MIL_HAB
0,353760,Peruíbe,263,5.55,11.03,1472.34,0,68352,3.85
1,350190,Amparo,336,6.09,10.71,1931.03,0,68008,4.94
2,351020,Capão Bonito,261,3.50,10.73,1310.42,0,46337,5.63
3,350660,Biritiba Mirim,136,5.42,11.03,1676.72,0,29683,4.58
4,353600,Parapuã,57,7.28,8.77,1149.48,0,10580,5.39

##### Conferir os dados

In [4]:
dados.shape
dados.isna().sum()

COD_MUNICIPIO              0
MUNICIPIO                  0
QTD_INTERNACOES            0
PERMANENCIA_MEDIA          0
TAXA_MORTALIDADE_PCT       0
VALOR_MEDIO_INTERNACAO     0
QTD_ESTAB_HOSPITALARES     0
POPULACAO                  0
INTERNACOES_POR_MIL_HAB    0
dtype: int64

In [5]:
dados = dados.dropna(subset=['POPULACAO'])
dados['QTD_ESTAB_HOSPITALARES'] = dados['QTD_ESTAB_HOSPITALARES'].fillna(0)